#define InitState 1
#define RunArms 2 
#define BumpRunArms 3 
#define MoveForward 4 
#define BumpExtendArms 5
#define BumpRetractArms 6
#define MoveOverBump 7 
#define FinalRunArms 9 
#define SystemStop 10
